INSERT INTO CodeStore (deleted, parentcodestore_codestore_id, name, deletable, linkname) VALUES
	('0', NULL, 'Currencies', 'false', 'Currencies'),
	('0', NULL, 'Packing units', 'false', 'Packing units'),
	('0', NULL, 'Order states', 'false', 'Order states'),
	('0', NULL, 'Tax keys', 'false', 'Tax keys'),
	('0', NULL, 'Street types', 'false', 'Street types'),
	('0', NULL, 'Countries', 'false', 'Countries'),
	('0', NULL, 'Payment types', 'false', 'Payment types'),
	('0', '1', 'RUB', 'false', 'RUB'),
	('0', '1', 'AFN', 'false', 'AFN'),
	('0', '1', 'EUR', 'false', 'EUR'),
	('0', '1', 'ALL', 'false', 'ALL'),
	('0', '1', 'DZD', 'false', 'DZD'),
	('0', '1', 'AOA', 'false', 'AOA'),
	('0', '1', 'XCD', 'false', 'XCD'),
	('0', '1', 'ARS', 'false', 'ARS'),
	('0', '1', 'AMD', 'false', 'AMD'),
	('0', '1', 'AWG', 'false', 'AWG'),
	('0', '1', 'SHP', 'false', 'SHP'),
	('0', '1', 'AUD', 'false', 'AUD'),
	('0', '1', 'AZN', 'false', 'AZN'),
	('0', '1', 'BSD', 'false', 'BSD'),
	('0', '1', 'BHD', 'false', 'BHD'),
	('0', '1', 'BDT', 'false', 'BDT'),
	('0', '1', 'BBD', 'false', 'BBD'),
	('0', '1', 'BYN', 'false', 'BYN'),
	('0', '1', 'BZD', 'false', 'BZD'),
	('0', '1', 'XOF', 'false', 'XOF'),
	('0', '1', 'BMD', 'false', 'BMD'),
	('0', '1', 'BTN', 'false', 'BTN'),
	('0', '1', 'INR', 'false', 'INR'),
	('0', '1', 'BOB', 'false', 'BOB'),
	('0', '1', 'USD', 'false', 'USD'),
	('0', '1', 'BAM', 'false', 'BAM'),
	('0', '1', 'BWP', 'false', 'BWP'),
	('0', '1', 'BRL', 'false', 'BRL'),
	('0', '1', 'BND', 'false', 'BND'),
	('0', '1', 'SGD', 'false', 'SGD'),
	('0', '1', 'BGN', 'false', 'BGN'),
	('0', '1', 'BIF', 'false', 'BIF'),
	('0', '1', 'KHR', 'false', 'KHR'),
	('0', '1', 'XAF', 'false', 'XAF'),
	('0', '1', 'CAD', 'false', 'CAD'),
	('0', '1', 'CVE', 'false', 'CVE'),
	('0', '1', 'KYD', 'false', 'KYD'),
	('0', '1', 'CLP', 'false', 'CLP'),
	('0', '1', 'CNY', 'false', 'CNY'),
	('0', '1', 'COP', 'false', 'COP'),
	('0', '1', 'KMF', 'false', 'KMF'),
	('0', '1', 'CDF', 'false', 'CDF'),
	('0', '1', 'NZD', 'false', 'NZD'),
	('0', '1', 'CRC', 'false', 'CRC'),
	('0', '1', 'CUP', 'false', 'CUP'),
	('0', '1', 'ANG', 'false', 'ANG'),
	('0', '1', 'CZK', 'false', 'CZK'),
	('0', '1', 'DKK', 'false', 'DKK'),
	('0', '1', 'DJF', 'false', 'DJF'),
	('0', '1', 'DOP', 'false', 'DOP'),
	('0', '1', 'EGP', 'false', 'EGP'),
	('0', '1', 'ERN', 'false', 'ERN'),
	('0', '1', 'SZL', 'false', 'SZL'),
	('0', '1', 'ZAR', 'false', 'ZAR'),
	('0', '1', 'ETB', 'false', 'ETB'),
	('0', '1', 'FKP', 'false', 'FKP'),
	('0', '1', 'GBP', 'false', 'GBP'),
	('0', '1', 'FJD', 'false', 'FJD'),
	('0', '1', 'XPF', 'false', 'XPF'),
	('0', '1', 'GMD', 'false', 'GMD'),
	('0', '1', 'GEL', 'false', 'GEL'),
	('0', '1', 'GHS', 'false', 'GHS'),
	('0', '1', 'GIP', 'false', 'GIP'),
	('0', '1', 'GTQ', 'false', 'GTQ'),
	('0', '1', 'GNF', 'false', 'GNF'),
	('0', '1', 'GYD', 'false', 'GYD'),
	('0', '1', 'HTG', 'false', 'HTG'),
	('0', '1', 'HNL', 'false', 'HNL'),
	('0', '1', 'HKD', 'false', 'HKD'),
	('0', '1', 'HUF', 'false', 'HUF'),
	('0', '1', 'ISK', 'false', 'ISK'),
	('0', '1', 'IDR', 'false', 'IDR'),
	('0', '1', 'IRR', 'false', 'IRR'),
	('0', '1', 'IQD', 'false', 'IQD'),
	('0', '1', 'ILS', 'false', 'ILS'),
	('0', '1', 'JMD', 'false', 'JMD'),
	('0', '1', 'JPY', 'false', 'JPY'),
	('0', '1', 'JOD', 'false', 'JOD'),
	('0', '1', 'KZT', 'false', 'KZT'),
	('0', '1', 'KES', 'false', 'KES'),
	('0', '1', 'KPW', 'false', 'KPW'),
	('0', '1', 'KRW', 'false', 'KRW'),
	('0', '1', 'KWD', 'false', 'KWD'),
	('0', '1', 'KGS', 'false', 'KGS'),
	('0', '1', 'LAK', 'false', 'LAK'),
	('0', '1', 'LBP', 'false', 'LBP'),
	('0', '1', 'LSL', 'false', 'LSL'),
	('0', '1', 'LRD', 'false', 'LRD'),
	('0', '1', 'LYD', 'false', 'LYD'),
	('0', '1', 'CHF', 'false', 'CHF'),
	('0', '1', 'MOP', 'false', 'MOP'),
	('0', '1', 'MGA', 'false', 'MGA'),
	('0', '1', 'MWK', 'false', 'MWK'),
	('0', '1', 'MYR', 'false', 'MYR'),
	('0', '1', 'MVR', 'false', 'MVR'),
	('0', '1', 'MRU', 'false', 'MRU'),
	('0', '1', 'MUR', 'false', 'MUR'),
	('0', '1', 'MXN', 'false', 'MXN'),
	('0', '1', 'MDL', 'false', 'MDL'),
	('0', '1', 'MNT', 'false', 'MNT'),
	('0', '1', 'MAD', 'false', 'MAD'),
	('0', '1', 'MZN', 'false', 'MZN'),
	('0', '1', 'MMK', 'false', 'MMK'),
	('0', '1', 'NAD', 'false', 'NAD'),
	('0', '1', 'NPR', 'false', 'NPR'),
	('0', '1', 'NIO', 'false', 'NIO'),
	('0', '1', 'NGN', 'false', 'NGN'),
	('0', '1', 'MKD', 'false', 'MKD'),
	('0', '1', 'TRY', 'false', 'TRY'),
	('0', '1', 'NOK', 'false', 'NOK'),
	('0', '1', 'OMR', 'false', 'OMR'),
	('0', '1', 'PKR', 'false', 'PKR'),
	('0', '1', 'PAB', 'false', 'PAB'),
	('0', '1', 'PGK', 'false', 'PGK'),
	('0', '1', 'PYG', 'false', 'PYG'),
	('0', '1', 'PEN', 'false', 'PEN'),
	('0', '1', 'PHP', 'false', 'PHP'),
	('0', '1', 'PLN', 'false', 'PLN'),
	('0', '1', 'QAR', 'false', 'QAR'),
	('0', '1', 'RON', 'false', 'RON'),
	('0', '1', 'RWF', 'false', 'RWF'),
	('0', '1', 'WST', 'false', 'WST'),
	('0', '1', 'STN', 'false', 'STN'),
	('0', '1', 'SAR', 'false', 'SAR'),
	('0', '1', 'RSD', 'false', 'RSD'),
	('0', '1', 'SCR', 'false', 'SCR'),
	('0', '1', 'SLE', 'false', 'SLE'),
	('0', '1', 'SBD', 'false', 'SBD'),
	('0', '1', 'SOS', 'false', 'SOS'),
	('0', '1', 'SSP', 'false', 'SSP'),
	('0', '1', 'LKR', 'false', 'LKR'),
	('0', '1', 'SDG', 'false', 'SDG'),
	('0', '1', 'SRD', 'false', 'SRD'),
	('0', '1', 'SEK', 'false', 'SEK'),
	('0', '1', 'SYP', 'false', 'SYP'),
	('0', '1', 'TWD', 'false', 'TWD'),
	('0', '1', 'TJS', 'false', 'TJS'),
	('0', '1', 'TZS', 'false', 'TZS'),
	('0', '1', 'THB', 'false', 'THB'),
	('0', '1', 'TOP', 'false', 'TOP'),
	('0', '1', 'TTD', 'false', 'TTD'),
	('0', '1', 'TND', 'false', 'TND'),
	('0', '1', 'TMT', 'false', 'TMT'),
	('0', '1', 'UGX', 'false', 'UGX'),
	('0', '1', 'UAH', 'false', 'UAH'),
	('0', '1', 'AED', 'false', 'AED'),
	('0', '1', 'UYU', 'false', 'UYU'),
	('0', '1', 'UZS', 'false', 'UZS'),
	('0', '1', 'VUV', 'false', 'VUV'),
	('0', '1', 'VES', 'false', 'VES'),
	('0', '1', 'VED', 'false', 'VED'),
	('0', '1', 'VND', 'false', 'VND'),
	('0', '1', 'YER', 'false', 'YER'),
	('0', '1', 'ZMW', 'false', 'ZMW'),
	('0', '2', 'Meter', 'false', 'Meter'),
	('0', '2', 'Centimeter', 'false', 'Centimeter'),
	('0', '2', 'Kilometer', 'false', 'Kilometer'),
	('0', '2', 'Foot', 'false', 'Foot'),
	('0', '2', 'Mile', 'false', 'Mile'),
	('0', '2', 'Kilogram', 'false', 'Kilogram'),
	('0', '2', 'Gram', 'false', 'Gram'),
	('0', '2', 'Pound', 'false', 'Pound'),
	('0', '2', 'Ounce', 'false', 'Ounce'),
	('0', '2', 'Ton', 'false', 'Ton'),
	('0', '2', 'Liter', 'false', 'Liter'),
	('0', '2', 'Milliliter', 'false', 'Milliliter'),
	('0', '2', 'Cubic centimeter', 'false', 'Cubic centimeter'),
	('0', '2', 'Gallon', 'false', 'Gallon'),
	('0', '2', 'Barrel', 'false', 'Barrel'),
	('0', '2', 'Second', 'false', 'Second'),
	('0', '2', 'Minute', 'false', 'Minute'),
	('0', '2', 'Hour', 'false', 'Hour'),
	('0', '2', 'Day', 'false', 'Day'),
	('0', '2', 'Week', 'false', 'Week'),
	('0', '2', 'Celsius degree', 'false', 'Celsius degree'),
	('0', '2', 'Fahrenheit degree', 'false', 'Fahrenheit degree'),
	('0', '2', 'Kelvin', 'false', 'Kelvin'),
	('0', '2', 'Square meter', 'false', 'Square meter'),
	('0', '2', 'Square centimeter', 'false', 'Square centimeter'),
	('0', '2', 'Hectare', 'false', 'Hectare'),
	('0', '2', 'Square mile', 'false', 'Square mile'),
	('0', '2', 'Acre', 'false', 'Acre'),
	('0', '3', 'Pending', 'false', 'Pending'),
	('0', '3', 'Processing', 'false', 'Processing'),
	('0', '3', 'Shipped', 'false', 'Shipped'),
	('0', '3', 'In Transit', 'false', 'In Transit'),
	('0', '3', 'Out for Delivery', 'false', 'Out for Delivery'),
	('0', '3', 'Delivered', 'false', 'Delivered'),
	('0', '3', 'Canceled', 'false', 'Canceled'),
	('0', '3', 'Returned', 'false', 'Returned'),
	('0', '3', 'Refunded', 'false', 'Refunded'),
	('0', '3', 'Failed', 'false', 'Failed'),
	('0', '4', '0', 'false', '0'),
	('0', '4', '5', 'false', '5'),
	('0', '4', '18', 'false', '18'),
	('0', '4', '27', 'false', '27'),
	('0', '5', 'Street', 'false', 'Street'),
	('0', '5', 'Avenue', 'false', 'Avenue'),
	('0', '5', 'Boulevard', 'false', 'Boulevard'),
	('0', '5', 'Lane', 'false', 'Lane'),
	('0', '5', 'Road', 'false', 'Road'),
	('0', '5', 'Drive', 'false', 'Drive'),
	('0', '5', 'Court', 'false', 'Court'),
	('0', '5', 'Square', 'false', 'Square'),
	('0', '5', 'Place', 'false', 'Place'),
	('0', '5', 'Terrace', 'false', 'Terrace'),
	('0', '5', 'Way', 'false', 'Way'),
	('0', '5', 'Alley', 'false', 'Alley'),
	('0', '5', 'Path', 'false', 'Path'),
	('0', '5', 'Highway', 'false', 'Highway'),
	('0', '5', 'Driveway', 'false', 'Driveway'),
	('0', '6', 'Afghanistan', 'false', 'Afghanistan'),
	('0', '6', 'Albania', 'false', 'Albania'),
	('0', '6', 'Algeria', 'false', 'Algeria'),
	('0', '6', 'Andorra', 'false', 'Andorra'),
	('0', '6', 'Angola', 'false', 'Angola'),
	('0', '6', 'Antigua and Barbuda', 'false', 'Antigua and Barbuda'),
	('0', '6', 'Argentina', 'false', 'Argentina'),
	('0', '6', 'Armenia', 'false', 'Armenia'),
	('0', '6', 'Australia', 'false', 'Australia'),
	('0', '6', 'Austria', 'false', 'Austria'),
	('0', '6', 'Azerbaijan', 'false', 'Azerbaijan'),
	('0', '6', 'The Bahamas', 'false', 'The Bahamas'),
	('0', '6', 'Bahrain', 'false', 'Bahrain'),
	('0', '6', 'Bangladesh', 'false', 'Bangladesh'),
	('0', '6', 'Barbados', 'false', 'Barbados'),
	('0', '6', 'Belarus', 'false', 'Belarus'),
	('0', '6', 'Belgium', 'false', 'Belgium'),
	('0', '6', 'Belize', 'false', 'Belize'),
	('0', '6', 'Benin', 'false', 'Benin'),
	('0', '6', 'Bhutan', 'false', 'Bhutan'),
	('0', '6', 'Bolivia', 'false', 'Bolivia'),
	('0', '6', 'Bosnia and Herzegovina', 'false', 'Bosnia and Herzegovina'),
	('0', '6', 'Botswana', 'false', 'Botswana'),
	('0', '6', 'Brazil', 'false', 'Brazil'),
	('0', '6', 'Brunei', 'false', 'Brunei'),
	('0', '6', 'Bulgaria', 'false', 'Bulgaria'),
	('0', '6', 'Burkina Faso', 'false', 'Burkina Faso'),
	('0', '6', 'Burundi', 'false', 'Burundi'),
	('0', '6', 'Cabo Verde', 'false', 'Cabo Verde'),
	('0', '6', 'Cambodia', 'false', 'Cambodia'),
	('0', '6', 'Cameroon', 'false', 'Cameroon'),
	('0', '6', 'Canada', 'false', 'Canada'),
	('0', '6', 'Central African Republic', 'false', 'Central African Republic'),
	('0', '6', 'Chad', 'false', 'Chad'),
	('0', '6', 'Chile', 'false', 'Chile'),
	('0', '6', 'China', 'false', 'China'),
	('0', '6', 'Colombia', 'false', 'Colombia'),
	('0', '6', 'Comoros', 'false', 'Comoros'),
	('0', '6', 'Congo, Democratic Republic of the', 'false', 'Congo, Democratic Republic of the'),
	('0', '6', 'Congo, Republic of the', 'false', 'Congo, Republic of the'),
	('0', '6', 'Costa Rica', 'false', 'Costa Rica'),
	('0', '6', 'Côte d’Ivoire', 'false', 'Côte d’Ivoire'),
	('0', '6', 'Croatia', 'false', 'Croatia'),
	('0', '6', 'Cuba', 'false', 'Cuba'),
	('0', '6', 'Cyprus', 'false', 'Cyprus'),
	('0', '6', 'Czech Republic', 'false', 'Czech Republic'),
	('0', '6', 'Denmark', 'false', 'Denmark'),
	('0', '6', 'Djibouti', 'false', 'Djibouti'),
	('0', '6', 'Dominica', 'false', 'Dominica'),
	('0', '6', 'Dominican Republic', 'false', 'Dominican Republic'),
	('0', '6', 'East Timor (Timor-Leste)', 'false', 'East Timor (Timor-Leste)'),
	('0', '6', 'Ecuador', 'false', 'Ecuador'),
	('0', '6', 'Egypt', 'false', 'Egypt'),
	('0', '6', 'El Salvador', 'false', 'El Salvador'),
	('0', '6', 'Equatorial Guinea', 'false', 'Equatorial Guinea'),
	('0', '6', 'Eritrea', 'false', 'Eritrea'),
	('0', '6', 'Estonia', 'false', 'Estonia'),
	('0', '6', 'Eswatini', 'false', 'Eswatini'),
	('0', '6', 'Ethiopia', 'false', 'Ethiopia'),
	('0', '6', 'Fiji', 'false', 'Fiji'),
	('0', '6', 'Finland', 'false', 'Finland'),
	('0', '6', 'France', 'false', 'France'),
	('0', '6', 'Gabon', 'false', 'Gabon'),
	('0', '6', 'The Gambia', 'false', 'The Gambia'),
	('0', '6', 'Georgia', 'false', 'Georgia'),
	('0', '6', 'Germany', 'false', 'Germany'),
	('0', '6', 'Ghana', 'false', 'Ghana'),
	('0', '6', 'Greece', 'false', 'Greece'),
	('0', '6', 'Grenada', 'false', 'Grenada'),
	('0', '6', 'Guatemala', 'false', 'Guatemala'),
	('0', '6', 'Guinea', 'false', 'Guinea'),
	('0', '6', 'Guinea-Bissau', 'false', 'Guinea-Bissau'),
	('0', '6', 'Guyana', 'false', 'Guyana'),
	('0', '6', 'Haiti', 'false', 'Haiti'),
	('0', '6', 'Honduras', 'false', 'Honduras'),
	('0', '6', 'Hungary', 'false', 'Hungary'),
	('0', '6', 'Iceland', 'false', 'Iceland'),
	('0', '6', 'India', 'false', 'India'),
	('0', '6', 'Indonesia', 'false', 'Indonesia'),
	('0', '6', 'Iran', 'false', 'Iran'),
	('0', '6', 'Iraq', 'false', 'Iraq'),
	('0', '6', 'Ireland', 'false', 'Ireland'),
	('0', '6', 'Israel', 'false', 'Israel'),
	('0', '6', 'Italy', 'false', 'Italy'),
	('0', '6', 'Jamaica', 'false', 'Jamaica'),
	('0', '6', 'Japan', 'false', 'Japan'),
	('0', '6', 'Jordan', 'false', 'Jordan'),
	('0', '6', 'Kazakhstan', 'false', 'Kazakhstan'),
	('0', '6', 'Kenya', 'false', 'Kenya'),
	('0', '6', 'Kiribati', 'false', 'Kiribati'),
	('0', '6', 'Korea, North', 'false', 'Korea, North'),
	('0', '6', 'Korea, South', 'false', 'Korea, South'),
	('0', '6', 'Kosovo', 'false', 'Kosovo'),
	('0', '6', 'Kuwait', 'false', 'Kuwait'),
	('0', '6', 'Kyrgyzstan', 'false', 'Kyrgyzstan'),
	('0', '6', 'Laos', 'false', 'Laos'),
	('0', '6', 'Latvia', 'false', 'Latvia'),
	('0', '6', 'Lebanon', 'false', 'Lebanon'),
	('0', '6', 'Lesotho', 'false', 'Lesotho'),
	('0', '6', 'Liberia', 'false', 'Liberia'),
	('0', '6', 'Libya', 'false', 'Libya'),
	('0', '6', 'Liechtenstein', 'false', 'Liechtenstein'),
	('0', '6', 'Lithuania', 'false', 'Lithuania'),
	('0', '6', 'Luxembourg', 'false', 'Luxembourg'),
	('0', '6', 'Madagascar', 'false', 'Madagascar'),
	('0', '6', 'Malawi', 'false', 'Malawi'),
	('0', '6', 'Malaysia', 'false', 'Malaysia'),
	('0', '6', 'Maldives', 'false', 'Maldives'),
	('0', '6', 'Mali', 'false', 'Mali'),
	('0', '6', 'Malta', 'false', 'Malta'),
	('0', '6', 'Marshall Islands', 'false', 'Marshall Islands'),
	('0', '6', 'Mauritania', 'false', 'Mauritania'),
	('0', '6', 'Mauritius', 'false', 'Mauritius'),
	('0', '6', 'Mexico', 'false', 'Mexico'),
	('0', '6', 'Micronesia, Federated States of', 'false', 'Micronesia, Federated States of'),
	('0', '6', 'Moldova', 'false', 'Moldova'),
	('0', '6', 'Monaco', 'false', 'Monaco'),
	('0', '6', 'Mongolia', 'false', 'Mongolia'),
	('0', '6', 'Montenegro', 'false', 'Montenegro'),
	('0', '6', 'Morocco', 'false', 'Morocco'),
	('0', '6', 'Mozambique', 'false', 'Mozambique'),
	('0', '6', 'Myanmar (Burma)', 'false', 'Myanmar (Burma)'),
	('0', '6', 'Namibia', 'false', 'Namibia'),
	('0', '6', 'Nauru', 'false', 'Nauru'),
	('0', '6', 'Nepal', 'false', 'Nepal'),
	('0', '6', 'Netherlands', 'false', 'Netherlands'),
	('0', '6', 'New Zealand', 'false', 'New Zealand'),
	('0', '6', 'Nicaragua', 'false', 'Nicaragua'),
	('0', '6', 'Niger', 'false', 'Niger'),
	('0', '6', 'Nigeria', 'false', 'Nigeria'),
	('0', '6', 'North Macedonia', 'false', 'North Macedonia'),
	('0', '6', 'Norway', 'false', 'Norway'),
	('0', '6', 'Oman', 'false', 'Oman'),
	('0', '6', 'Pakistan', 'false', 'Pakistan'),
	('0', '6', 'Palau', 'false', 'Palau'),
	('0', '6', 'Panama', 'false', 'Panama'),
	('0', '6', 'Papua New Guinea', 'false', 'Papua New Guinea'),
	('0', '6', 'Paraguay', 'false', 'Paraguay'),
	('0', '6', 'Peru', 'false', 'Peru'),
	('0', '6', 'Philippines', 'false', 'Philippines'),
	('0', '6', 'Poland', 'false', 'Poland'),
	('0', '6', 'Portugal', 'false', 'Portugal'),
	('0', '6', 'Qatar', 'false', 'Qatar'),
	('0', '6', 'Romania', 'false', 'Romania'),
	('0', '6', 'Russia', 'false', 'Russia'),
	('0', '6', 'Rwanda', 'false', 'Rwanda'),
	('0', '6', 'Saint Kitts and Nevis', 'false', 'Saint Kitts and Nevis'),
	('0', '6', 'Saint Lucia', 'false', 'Saint Lucia'),
	('0', '6', 'Saint Vincent and the Grenadines', 'false', 'Saint Vincent and the Grenadines'),
	('0', '6', 'Samoa', 'false', 'Samoa'),
	('0', '6', 'San Marino', 'false', 'San Marino'),
	('0', '6', 'Sao Tome and Principe', 'false', 'Sao Tome and Principe'),
	('0', '6', 'Saudi Arabia', 'false', 'Saudi Arabia'),
	('0', '6', 'Senegal', 'false', 'Senegal'),
	('0', '6', 'Serbia', 'false', 'Serbia'),
	('0', '6', 'Seychelles', 'false', 'Seychelles'),
	('0', '6', 'Sierra Leone', 'false', 'Sierra Leone'),
	('0', '6', 'Singapore', 'false', 'Singapore'),
	('0', '6', 'Slovakia', 'false', 'Slovakia'),
	('0', '6', 'Slovenia', 'false', 'Slovenia'),
	('0', '6', 'Solomon Islands', 'false', 'Solomon Islands'),
	('0', '6', 'Somalia', 'false', 'Somalia'),
	('0', '6', 'South Africa', 'false', 'South Africa'),
	('0', '6', 'Spain', 'false', 'Spain'),
	('0', '6', 'Sri Lanka', 'false', 'Sri Lanka'),
	('0', '6', 'Sudan', 'false', 'Sudan'),
	('0', '6', 'Sudan, South', 'false', 'Sudan, South'),
	('0', '6', 'Suriname', 'false', 'Suriname'),
	('0', '6', 'Sweden', 'false', 'Sweden'),
	('0', '6', 'Switzerland', 'false', 'Switzerland'),
	('0', '6', 'Syria', 'false', 'Syria'),
	('0', '6', 'Taiwan', 'false', 'Taiwan'),
	('0', '6', 'Tajikistan', 'false', 'Tajikistan'),
	('0', '6', 'Tanzania', 'false', 'Tanzania'),
	('0', '6', 'Thailand', 'false', 'Thailand'),
	('0', '6', 'Togo', 'false', 'Togo'),
	('0', '6', 'Tonga', 'false', 'Tonga'),
	('0', '6', 'Trinidad and Tobago', 'false', 'Trinidad and Tobago'),
	('0', '6', 'Tunisia', 'false', 'Tunisia'),
	('0', '6', 'Turkey', 'false', 'Turkey'),
	('0', '6', 'Turkmenistan', 'false', 'Turkmenistan'),
	('0', '6', 'Tuvalu', 'false', 'Tuvalu'),
	('0', '6', 'Uganda', 'false', 'Uganda'),
	('0', '6', 'Ukraine', 'false', 'Ukraine'),
	('0', '6', 'United Arab Emirates', 'false', 'United Arab Emirates'),
	('0', '6', 'United Kingdom', 'false', 'United Kingdom'),
	('0', '6', 'United States', 'false', 'United States'),
	('0', '6', 'Uruguay', 'false', 'Uruguay'),
	('0', '6', 'Uzbekistan', 'false', 'Uzbekistan'),
	('0', '6', 'Vanuatu', 'false', 'Vanuatu'),
	('0', '6', 'Vatican City', 'false', 'Vatican City'),
	('0', '6', 'Venezuela', 'false', 'Venezuela'),
	('0', '6', 'Vietnam', 'false', 'Vietnam'),
	('0', '6', 'Yemen', 'false', 'Yemen'),
	('0', '6', 'Zambia', 'false', 'Zambia'),
	('0', '6', 'Zimbabwe', 'false', 'Zimbabwe'),
	('0', '7', 'Credit Card', 'false', 'Credit Card'),
	('0', '7', 'Debit Card', 'false', 'Debit Card'),
	('0', '7', 'PayPal', 'false', 'PayPal'),
	('0', '7', 'Bank Transfer', 'false', 'Bank Transfer'),
	('0', '7', 'Cryptocurrency', 'false', 'Cryptocurrency'),
	('0', '7', 'Cash', 'false', 'Cash'),
	('0', '7', 'Mobile Payment', 'false', 'Mobile Payment'),
	('0', '7', 'Cheque', 'false', 'Cheque'),
	('0', '7', 'Prepaid Card', 'false', 'Prepaid Card'),
	('0', '7', 'Gift Card', 'false', 'Gift Card')